### ISSUE TITLE
Endless loop when used from :prep-tasks

### ISSUE THREAD

**Issue by Skinney** [lynaghk/cljx#63] opened 2015-01-09 00:15 UTC
I currently have this in my project.clj:

                       :prep-tasks [["clean"]
                                    ["cljx" "once"]
                                    ["cljs-prod"]
                                    ["garden" "once"]
                                    ["javac"]
                                    ["compile" ":all"]]

With both 0.4.0 and 0.5.0, cljx seems trigger this sequence of events to be performed again and again. In 0.4.0, cljx is run before the others, in 0.5.0 it seems that cljx isn't run at all (possibly related to #60 )

I recently fixed this in lein-garden, maybe it's something similar here: https://github.com/Skinney/lein-garden/commit/6dc65a2193fca84838b34334a37c6d2b23b7e799

**Comment by cemerick** [comment] 2015-02-13 14:22
Seems like a dupe of #60? I believe this is fixed now on master, available in `[org.clojars.cemerick/cljx "0.6.0-SNAPSHOT"]` until a real release is cut. Confirmation of the fix is appreciated.

**Closed by cemerick** 2015-02-13 14:22 UTC
